#!/bin/bash
. /etc/ppp/ip-down $1 $2 $3 $4 $5 $6

WAN_IF=#DHCP_IF#
PPP_IFACE="$1"

logger "accel-ppp if-down"

iptables -D INPUT -i $WAN_IF -p tcp --dport 1723 -j ACCEPT
iptables -D INPUT -i $WAN_IF -p gre -j ACCEPT
iptables -D FORWARD -i ppp+ -o $WAN_IF -j ACCEPT
iptables -D FORWARD -i $WAN_IF -o ppp+ -j ACCEPT
iptables -D POSTROUTING -t nat -o  $WAN_IF -j MASQUERADE
