#!/bin/bash
#
#  Geert Stappers git things
#
#  What he usually does after a git clone
#
git config user.name "Geert Stappers"
git config user.email stappers@debian.org

git config url."rosa.stappers.it:/srv/git/pkg-radvd".PushInsteadOf http://stappers.it/git/pkg-radvd

# l l
