#!/bin/bash

CONFIG=/etc/wan-mode/00_setting
RUN=/etc/wan-mode/01-start.sh

. ${CONFIG}

printf "\033[1;33m================================================================================\033[m\n"
printf "\033[1;32mTopology:\033[m\n"
printf "server: PPPoE/PPTP/L2TP/DS-Lite\n"
printf "LAN PC: 192.168.0.x \n"
printf "\n"
printf "<Manager Network>---(${MANAGER_IF},${MANAGER_IP})--\n"
printf "      <192.168.110.x>---(${AFTR_WAN_IF,${AFTR_WAN_IP})server(${AFTR_LAN_IF},${LAN_IP})---(WAN)DUT---<LAN PC>\n"
printf "                        (${AFTR_WAN_IPv6})    (    ${AFTR_LAN_IPv6})  \n"
printf "                                                       \n"
printf "                     <Internet>---(WAN)RG(${GW_IP})-----\n"
printf "\033[1;33m================================================================================\033[m\n"
printf "MODIFY ${CONFIG} for DUT WAN MAC ADDRESS\n"
printf "RUN ${RUN} to start service\n"
if [ ${ACCEL_PPP} == 1 ]; then
printf "\033[1;33m================================================================================\033[m\n"
printf "\033[1;32mPPPoE:\033[m\n"
printf " username: 1\n password: 1\033[m\n"
printf " GW: ${PPP_IP} \n IP: ${IPPOOL_PPPOE} \033[m\n"
printf " USE pppoe/pppoe will get fix IP: ${IP_PPPOE}\n"
printf "\033[1;33m================================================================================\033[m\n"
printf "\033[1;32mPPTP:\033[m\n"
printf " Server IP: ${LAN_IP}\n"
printf " username: 1\n password: 1\033[m\n"
printf " GW: ${PPP_IP} \n IP: ${IPPOOL_PPTP} \033[m\n"
printf " USE pptp/pptp will get fix IP: ${IP_PPTP}\n"
printf "\033[1;33m================================================================================\033[m\n"
printf "\033[1;32mL2TP:\033[m\n"
printf " Server IP: ${LAN_IP}\n"
printf " username: 1\n password: 1\033[m\n"
printf " GW: ${PPP_IP} \n IP: ${IPPOOL_L2TP} \033[m\n"
printf " USE l2tp/l2tp will get fix IP: ${IP_L2TP}\n"
fi
if [ ${DS_LITE} == 1 ]; then
printf "\033[1;33m================================================================================\033[m\n"
printf "\033[1;32mDS-lite:\033[m\n"
printf " LAN PC with DHCP\n"
printf " IPv6: ping -6 ${AFTR_WAN_IPv6} \n"
printf " IPv4: ping ${AFTR_WAN_IP} \n"
fi
printf "\033[1;33m================================================================================\033[m\n"
printf "\033[1;32mDHCPv4:\033[m\n"
printf " GW: ${GW_IP} \n "
printf " IP pool: ${IPPOOL_DHCPv4_START}~${IPPOOL_DHCPv4_END} \033[m\n"
printf "\033[1;33m================================================================================\033[m\n"
printf "\033[1;32mDHCPv6:\033[m\n"
if [ ${IPV6MODE} == 2 ]; then
printf " IP: ${ROUTER_IPv6} \n "
else 
printf " IP: ? \n "
fi
printf " GW: ${AFTR_LAN_IPv6} \n "
printf " IP pool: ${DHCPv6_IPv6_START}~${DHCPv6_IPv6_END} \033[m\n"
printf "\033[1;33m================================================================================\033[m\n"
